WIP: changes for target independent build
PandABlocks/PandABlocks-rootfs pull request #6
Opened 2020-10-12 09:50 UTC by glennchid

Target specific boot sources (FSBL/boot.bin, devicetree)  moved to FPGA repo.
NB. Merge should only be made when corresponding change made in other repo.

Still to do:
- led deamon

2021-04-07 10:17 UTC, Araneidae commented
Looks like there are some merge conflicts that will need to be resolved first.

2021-04-07 10:28 UTC, Araneidae requested changes
So it looks as if this merge simply removes the boot files.  Without the extra target specific settings in `Makefile` I'm happy to merge this.

2021-04-07 10:28 UTC, Araneidae commented on Makefile
> +#    $$(error Unknown PLATFORM specified. Must be 'zynq' or 'zynqmp')
I'm really not hugely happy with this big block of code here.
1. It's commented out but substantial
2. It's target specific, so shouldn't be in this top level file
Can this be placed in a separate file and either made real or not include in this merge.

2021-08-20 10:50 UTC, thomascobb commented
Superseded by master

2021-08-20 10:50 UTC, closed without merging